// The player-facing game: three screens, switched by state.view -- a home screen
// listing every set of levels (Michael's own review tool, at ?set=home -- not
// part of the real front page, see below), a level-select grid within whichever
// set was chosen (or linked to with ?set=), and the board itself. The rules
// (move, previewPushes, isWon, ...) are in engine.js, the levels in levels.js
// and the board drawing (drawBoard, CELL) in render.js, all loaded before this
// file. bench.html is the developer's test bench, this is the game.
//
// A bare link (no ?set=) is the real front page: Seize the Crown's level-select
// screen, directly, the way it worked before the home screen existed. Every
// other set (dancefloor, mud, potions, the bridge generator) is still live and
// reachable by anyone who knows the URL -- there's no backend to actually hide
// anything behind -- it's just not what a visitor lands on or is shown a link to.
const KEY_DIRECTIONS = {
  ArrowUp: "up", ArrowDown: "down", ArrowLeft: "left", ArrowRight: "right",
  w: "up", s: "down", a: "left", d: "right",
  W: "up", S: "down", A: "left", D: "right"
};

const DEATH_TEXT = {
  lava: "You stepped into the lava. The level has restarted.",
  edge: "You stepped off the edge into the lava. The level has restarted.",
  abyss: "You stepped into the abyss. The level has restarted."
};
const REFUSAL_TEXT = {
  wall: "There's a wall there.",
  "stack-blocked": "That stack is against a wall and won't move.",
  lava: "That's lava, so the move was refused.",
  edge: "That's the edge of the board (lava), so the move was refused.",
  abyss: "That's the abyss, so the move was refused."
};

// What the how-to-play says first, by objective. A level's objective is
// `objective` in its level-list entry ("reach" if it has none).
const OBJECTIVE_HELP = {
  reach: "Seize the crown! Reach it to win the level.",
  lava: "Fill in all the lava. Blocks left over don't matter.",
  all: "Clear the dancefloor! Get rid of every bit of lava and every block. A block can only be removed by pushing it into infinite lava."
};

// Every set of levels the game offers, keyed by the URL's `?set=` (the curated set is
// "crown", also what a bare URL with no `?set=` opens straight into, for links from
// before there was a home screen). Each keeps its own saved progress.
const ALL_SETS = {
  crown: { levels: CURATED_LEVELS, key: "magmamia.solved.v1", title: "Seize the Crown", blurb: "The core game: reach the crown." },
  dancefloor: { levels: DANCEFLOOR_CANDIDATES, key: "magmamia.solved.dancefloor3.v1", title: "Clear the Dancefloor", blurb: "Candidates, latest round: get rid of every bit of lava and every block." },
  dancefloor2: { levels: DANCEFLOOR_ROUND_2, key: "magmamia.solved.dancefloor2.v1", title: "Clear the Dancefloor (round 2)", blurb: "Clear the dancefloor candidates, an earlier round." },
  dancefloor1: { levels: DANCEFLOOR_ROUND_1, key: "magmamia.solved.dancefloor.v1", title: "Clear the Dancefloor (round 1)", blurb: "Clear the dancefloor candidates, the first round." },
  mud: { levels: MUD_ROUND_2, key: "magmamia.solved.mud2.v1", title: "There will be mud", blurb: "Seize the crown, with waterlogged blocks in the mix." },
  mud1: { levels: MUD_ROUND_1, key: "magmamia.solved.mud.v1", title: "There will be mud (round 1)", blurb: "There will be mud, the first, hand-built round." },
  potion: { levels: POTION_LEVELS, key: "magmamia.solved.potion.v1", title: "Potions", blurb: "An early experiment: a potion buys one safe step onto lava (no name yet)." },
  bridgeDense: { levels: BRIDGE_DENSE, key: "magmamia.solved.bridgeDense.v1", title: "Bridges (dense)", blurb: "Generated by joining lava-locked islands one bridge at a time. Busier lava." },
  bridgeOpen: { levels: BRIDGE_OPEN, key: "magmamia.solved.bridgeOpen.v1", title: "Bridges (open)", blurb: "The same generator, sparser lava -- calmer to look at, compare against Bridges (dense)." }
};
// The order sets are listed on the home screen.
const SET_ORDER = ["crown", "dancefloor", "dancefloor2", "dancefloor1", "mud", "mud1", "potion", "bridgeDense", "bridgeOpen"];

// The raw ?set= value, whatever it is -- not filtered to ALL_SETS, since the
// caller also needs to recognise the reserved value "home" (see below).
function requestedSetParam() {
  try {
    return new URLSearchParams(window.location.search).get("set");
  } catch {
    return null;
  }
}

const GENTLE_KEY = "magmamia.gentle.v1";
const PREVIEW_KEY = "magmamia.preview.v1";

const state = {
  view: "home", // "home" (pick a set), "levels" (pick a level within one) or "play".
  setKey: null, // Which of ALL_SETS is open, or null on the home screen.
  levelIndex: 0,
  initial: null,
  current: null,
  history: [], // Every earlier state, oldest first; its length is the move count.
  pushCounts: [], // Parallel to history: how many pushes had been made at each of those states.
  pushes: 0, // Pushes so far. The level's `optimum` is the fewest pushes that solve it.
  message: "",
  messageKind: "",
  solved: new Set(), // Indexes solved so far in the open set, remembered between visits.
  gentle: false, // Refuse lava moves instead of dying.
  preview: false, // Tag the cells a push would drop blocks on. Opt-in, off by default.
  hasPotions: false // Whether the current level uses potions at all, set by startLevel.
};

function currentSet() {
  return state.setKey ? ALL_SETS[state.setKey] : null;
}
function currentLevels() {
  const set = currentSet();
  return set ? set.levels : [];
}
function firstUnsolvedLevel() {
  const levels = currentLevels();
  const index = levels.findIndex((_, i) => !state.solved.has(i));
  return index >= 0 ? index : 0;
}

const elements = {
  homeScreen: document.querySelector("#home-screen"),
  modeList: document.querySelector("#mode-list"),
  levelsScreen: document.querySelector("#levels-screen"),
  levelsHomeButton: document.querySelector("#levels-home-button"),
  levelsContinueButton: document.querySelector("#levels-continue-button"),
  levelsTitle: document.querySelector("#levels-title"),
  levelsSubtitle: document.querySelector("#levels-subtitle"),
  levelsGrid: document.querySelector("#levels-grid"),
  playScreen: document.querySelector("#play-screen"),
  playLevelsButton: document.querySelector("#play-levels-button"),
  infoButton: document.querySelector("#info-button"),
  infoPanel: document.querySelector("#info-panel"),
  gentle: document.querySelector("#gentle-lava"),
  preview: document.querySelector("#show-preview"),
  board: document.querySelector("#board"),
  status: document.querySelector("#status"),
  undo: document.querySelector("#undo-button"),
  restart: document.querySelector("#restart-button"),
  next: document.querySelector("#next-button"),
  dpadButtons: [...document.querySelectorAll(".dpad button")],
  objectiveHelp: document.querySelector("#objective-help"),
  title: document.querySelector("#game-title")
};

loadPreferences();
elements.gentle.checked = state.gentle;
elements.preview.checked = state.preview;
elements.infoButton.addEventListener("click", toggleInfo);
elements.gentle.addEventListener("change", () => {
  state.gentle = elements.gentle.checked;
  savePreference(GENTLE_KEY, state.gentle ? "1" : "0");
});
elements.preview.addEventListener("change", () => {
  state.preview = elements.preview.checked;
  savePreference(PREVIEW_KEY, state.preview ? "1" : "0");
  render();
});
elements.undo.addEventListener("click", undo);
elements.restart.addEventListener("click", restart);
elements.next.addEventListener("click", () => startLevel(state.levelIndex + 1));
for (const button of elements.dpadButtons) {
  button.addEventListener("click", () => attemptMove(button.dataset.dir));
}
elements.board.addEventListener("click", handleBoardClick);
elements.levelsHomeButton.addEventListener("click", goHome);
elements.levelsContinueButton.addEventListener("click", () => startLevel(firstUnsolvedLevel()));
elements.playLevelsButton.addEventListener("click", () => openLevels(state.setKey));
document.addEventListener("keydown", handleKeyDown);

// The real front page is just Seize the Crown -- a bare link (from the hub site,
// or index.html with no query string) goes straight to it, the way it did
// before the home screen existed. The home screen (every set, for Michael's own
// review, not for a visitor) is reachable at ?set=home; an actual set still
// opens directly at ?set=<key>, unchanged.
const requestedParam = requestedSetParam();
if (requestedParam && ALL_SETS[requestedParam]) openLevels(requestedParam);
else if (requestedParam === "home") goHome();
else openLevels("crown");

// --- Moving between the three screens ---------------------------------------

function goHome() {
  state.view = "home";
  state.setKey = null;
  render();
}

function openLevels(key) {
  state.setKey = key;
  state.view = "levels";
  loadSetPreferences();
  render();
}

// --- Preferences: two global display settings, plus each set's own solved list --

// Browser storage may be missing or blocked, so every use is wrapped: the game
// works the same without it, it just forgets progress and settings.
function loadPreferences() {
  try {
    state.gentle = window.localStorage.getItem(GENTLE_KEY) === "1";
    state.preview = window.localStorage.getItem(PREVIEW_KEY) === "1"; // Off unless turned on.
  } catch {
    /* No saved preferences. */
  }
}

function loadSetPreferences() {
  state.solved = new Set();
  try {
    const solved = JSON.parse(window.localStorage.getItem(currentSet().key) || "[]");
    if (Array.isArray(solved)) solved.forEach((i) => Number.isInteger(i) && state.solved.add(i));
  } catch {
    /* No saved progress for this set. */
  }
}

// A set's solved count read straight from storage, so the home screen can show every
// set's progress without having to open each one first.
function solvedCountFor(key) {
  try {
    const solved = JSON.parse(window.localStorage.getItem(ALL_SETS[key].key) || "[]");
    return Array.isArray(solved) ? solved.length : 0;
  } catch {
    return 0;
  }
}

function savePreference(key, value) {
  try {
    window.localStorage.setItem(key, value);
  } catch {
    /* Progress just isn't remembered. */
  }
}

function toggleInfo() {
  const open = elements.infoPanel.hidden;
  elements.infoPanel.hidden = !open;
  elements.infoButton.setAttribute("aria-expanded", String(open));
}

// --- Playing a level ---------------------------------------------------------

function startLevel(index) {
  const levels = currentLevels();
  if (index < 0 || index >= levels.length) return;
  state.view = "play";
  state.levelIndex = index;
  state.initial = parseLevel(levels[index].text);
  state.hasPotions = state.initial.potions.some((p) => p === 1); // Only show the count if the level actually uses them.
  resetHistory();
  setMessage("", "");
  render();
}

function setMessage(text, kind) {
  state.message = text;
  state.messageKind = kind;
}

function objectiveOf(levelIndex) {
  return currentLevels()[levelIndex].objective || "reach";
}

function isSolved() {
  return isWon(state.current, objectiveOf(state.levelIndex));
}

function attemptMove(directionName) {
  if (isSolved()) return;
  const outcome = move(state.current, directionName, { lavaFatal: !state.gentle });
  if (outcome.result === "moved" || outcome.result === "pushed") {
    state.history.push(state.current);
    state.pushCounts.push(state.pushes);
    if (outcome.result === "pushed") state.pushes += 1;
    state.current = outcome.state;
    if (outcome.pickedUpPotion) setMessage("Picked up a potion.", "");
    else if (outcome.usedPotion) setMessage("The potion saved you -- but it's used up, so don't step onto lava again next.", "");
    else setMessage("", "");
    if (isSolved()) {
      state.solved.add(state.levelIndex);
      savePreference(currentSet().key, JSON.stringify([...state.solved]));
    }
  } else if (outcome.result === "refused") {
    setMessage(REFUSAL_TEXT[outcome.reason], "");
  } else {
    // Died: the level restarts, and with it the move count and undo history.
    resetHistory();
    setMessage(DEATH_TEXT[outcome.reason], "died");
  }
  render();
}

function undo() {
  if (state.history.length === 0) return;
  state.current = state.history.pop();
  state.pushes = state.pushCounts.pop();
  setMessage("", "");
  render();
}

function resetHistory() {
  state.current = state.initial;
  state.history = [];
  state.pushCounts = [];
  state.pushes = 0;
}

function restart() {
  resetHistory();
  setMessage("", "");
  render();
}

function handleKeyDown(event) {
  if (event.ctrlKey || event.metaKey || event.altKey) return;
  const tag = event.target.tagName;
  if (tag === "INPUT" || tag === "SELECT" || tag === "TEXTAREA") return;
  if (state.view !== "play") return;
  const directionName = KEY_DIRECTIONS[event.key];
  if (directionName) {
    event.preventDefault();
    attemptMove(directionName);
  } else if (event.key === "z" || event.key === "Z") {
    undo();
  } else if (event.key === "r" || event.key === "R") {
    restart();
  } else if (event.key === "Enter" && isSolved() && !elements.next.hidden) {
    startLevel(state.levelIndex + 1);
  }
}

// A click on a square next to the player moves that way; anything else is ignored.
function handleBoardClick(event) {
  const s = state.current;
  const rect = elements.board.getBoundingClientRect();
  const scale = (s.cols * CELL) / rect.width;
  const x = Math.floor(((event.clientX - rect.left) * scale) / CELL);
  const y = Math.floor(((event.clientY - rect.top) * scale) / CELL);
  const dx = x - (s.player % s.cols);
  const dy = y - Math.floor(s.player / s.cols);
  if (Math.abs(dx) + Math.abs(dy) !== 1) return;
  const directionName = Object.keys(DIRECTIONS).find((name) => DIRECTIONS[name].dx === dx && DIRECTIONS[name].dy === dy);
  attemptMove(directionName);
}

// --- Rendering ----------------------------------------------------------------

function render() {
  elements.homeScreen.hidden = state.view !== "home";
  elements.levelsScreen.hidden = state.view !== "levels";
  elements.playScreen.hidden = state.view !== "play";
  if (state.view === "home") renderHome();
  else if (state.view === "levels") renderLevels();
  else renderPlay();
}

function renderHome() {
  elements.modeList.replaceChildren();
  for (const key of SET_ORDER) {
    const set = ALL_SETS[key];
    const button = document.createElement("button");
    button.type = "button";
    button.className = "mode-card";
    const title = document.createElement("span");
    title.className = "mode-title";
    title.textContent = set.title;
    const blurb = document.createElement("span");
    blurb.className = "mode-blurb";
    blurb.textContent = set.blurb;
    const progress = document.createElement("span");
    progress.className = "mode-progress";
    progress.textContent = `${solvedCountFor(key)}/${set.levels.length} solved`;
    button.append(title, blurb, progress);
    button.addEventListener("click", () => openLevels(key));
    elements.modeList.append(button);
  }
}

function renderLevels() {
  const set = currentSet();
  elements.levelsTitle.textContent = set.title;
  elements.levelsSubtitle.textContent = set.blurb;
  const allSolved = state.solved.size >= set.levels.length;
  elements.levelsContinueButton.hidden = allSolved;
  elements.levelsContinueButton.textContent = state.solved.size === 0 ? "Start →" : "Continue →";
  const next = firstUnsolvedLevel();
  elements.levelsGrid.replaceChildren();
  set.levels.forEach((_, index) => {
    const button = document.createElement("button");
    button.type = "button";
    button.textContent = String(index + 1);
    button.className = "level-button";
    if (state.solved.has(index)) button.classList.add("is-solved");
    if (!allSolved && index === next) button.classList.add("is-current");
    button.setAttribute("aria-label", `Level ${index + 1}${state.solved.has(index) ? ", solved" : ""}`);
    button.addEventListener("click", () => startLevel(index));
    elements.levelsGrid.append(button);
  });
}

function renderPlay() {
  const set = currentSet();
  elements.title.textContent = state.setKey === "crown" ? "Magma Mia!" : `Magma Mia! — ${set.title}`;
  elements.objectiveHelp.textContent = OBJECTIVE_HELP[objectiveOf(state.levelIndex)];
  // Tags for where a push from here would drop blocks (see previewPushes).
  const chips = state.preview && !isSolved() ? previewPushes(state.current).flatMap((push) => push.landings) : [];
  drawBoard(elements.board, state.current, { chips });
  renderStatus();
  elements.undo.disabled = state.history.length === 0;
  elements.next.hidden = !(isSolved() && state.levelIndex + 1 < currentLevels().length);
}

function renderStatus() {
  const moves = state.history.length;
  elements.status.className = "status";
  if (isSolved()) {
    const last = state.levelIndex + 1 >= currentLevels().length;
    const lastSuffix = last ? " That's the last level for now." : "";
    // Push optimisation (moves, pushes, and the optimum comparison) is the point
    // of "Clear the dancefloor" -- tidying up efficiently is the game there. It
    // isn't the point of the other objectives, so their solved message stays plain.
    if (objectiveOf(state.levelIndex) === "all") {
      const optimum = currentLevels()[state.levelIndex].optimum;
      const pushes = `${state.pushes} ${state.pushes === 1 ? "push" : "pushes"}`;
      const versus = !optimum ? "" : state.pushes <= optimum ? " That's the optimum!" : ` The optimum is ${optimum}.`;
      elements.status.textContent = `Solved in ${moves} ${moves === 1 ? "move" : "moves"}, ${pushes}.${versus}${lastSuffix}`;
    } else {
      elements.status.textContent = `Solved!${lastSuffix}`;
    }
    elements.status.classList.add("is-won");
  } else {
    const potions = state.hasPotions ? ` · Potions: ${state.current.carried}` : "";
    const prefix = `Level ${state.levelIndex + 1} · Moves: ${moves} · Pushes: ${state.pushes}${potions}`;
    elements.status.textContent = state.message ? `${prefix} · ${state.message}` : prefix;
    if (state.messageKind === "died") elements.status.classList.add("is-died");
  }
}
