// The player-facing game: four screens, switched by state.view -- a splash
// (Seize the Crown's own front page, see below), a home screen listing every
// set of levels (Michael's own review tool, at ?set=home -- not part of the
// real front page), a level-select grid within whichever set was chosen (or
// linked to with ?set=), and the board itself (which also carries its own
// level queue, for jumping around without leaving it). The rules (move,
// previewPushes, isWon, ...) are in engine.js, the levels in levels.js and the
// board drawing (drawBoard, CELL) in render.js, all loaded
// before this file. bench.html is the developer's test bench, this is the game.
//
// A bare link (no ?set=) is the real front page: the splash, with "Enter the
// dungeon!" leading into Seize the Crown directly (skipping the level-select
// grid, which the play screen's own queue makes largely redundant for it).
// Every other set (dancefloor, mud, potions, the bridge generator) is still
// live and reachable by anyone who knows the URL -- there's no backend to
// actually hide anything behind -- it's just not what a visitor lands on or is
// shown a link to.
const KEY_DIRECTIONS = {
  ArrowUp: "up", ArrowDown: "down", ArrowLeft: "left", ArrowRight: "right",
  w: "up", s: "down", a: "left", d: "right",
  W: "up", S: "down", A: "left", D: "right"
};

const DEATH_TEXT = {
  lava: "You stepped into the lava. The level has restarted.",
  edge: "You stepped off the edge into the lava. The level has restarted.",
  abyss: "You stepped into the abyss. The level has restarted."
};
const REFUSAL_TEXT = {
  wall: "There's a wall there.",
  "stack-blocked": "That stack is against a wall and won't move.",
  lava: "That's lava, so the move was refused.",
  edge: "That's the edge of the board (lava), so the move was refused.",
  abyss: "That's the abyss, so the move was refused."
};

// What the how-to-play says first, by objective. A level's objective is
// `objective` in its level-list entry ("reach" if it has none).
const OBJECTIVE_HELP = {
  reach: "Seize the crown! Reach it to win the level.",
  lava: "Fill in all the lava. Blocks left over don't matter.",
  all: "Clear the dancefloor! Get rid of every bit of lava and every block. A block can only be removed by pushing it into infinite lava."
};

// Every set of levels the game offers, keyed by the URL's `?set=` (the curated set is
// "crown", also what a bare URL with no `?set=` opens straight into, for links from
// before there was a home screen). Each keeps its own saved progress.
const ALL_SETS = {
  crown: { levels: CURATED_LEVELS, key: "magmamia.solved.v1", title: "Seize the Crown", blurb: "The core game: reach the crown." },
  dancefloor: { levels: DANCEFLOOR_CANDIDATES, key: "magmamia.solved.dancefloor3.v1", title: "Clear the Dancefloor", blurb: "Candidates, latest round: get rid of every bit of lava and every block." },
  dancefloor2: { levels: DANCEFLOOR_ROUND_2, key: "magmamia.solved.dancefloor2.v1", title: "Clear the Dancefloor (round 2)", blurb: "Clear the dancefloor candidates, an earlier round." },
  dancefloor1: { levels: DANCEFLOOR_ROUND_1, key: "magmamia.solved.dancefloor.v1", title: "Clear the Dancefloor (round 1)", blurb: "Clear the dancefloor candidates, the first round." },
  mud: { levels: MUD_ROUND_2, key: "magmamia.solved.mud2.v1", title: "There will be mud", blurb: "Seize the crown, with waterlogged blocks in the mix." },
  mud1: { levels: MUD_ROUND_1, key: "magmamia.solved.mud.v1", title: "There will be mud (round 1)", blurb: "There will be mud, the first, hand-built round." },
  potion: { levels: POTION_LEVELS, key: "magmamia.solved.potion.v1", title: "Potions", blurb: "An early experiment: a potion buys one safe step onto lava (no name yet)." },
  bridgeDense: { levels: BRIDGE_DENSE, key: "magmamia.solved.bridgeDense.v1", title: "Bridges (dense)", blurb: "Generated by joining lava-locked islands one bridge at a time. Busier lava." },
  bridgeOpen: { levels: BRIDGE_OPEN, key: "magmamia.solved.bridgeOpen.v1", title: "Bridges (open)", blurb: "The same generator, sparser lava -- calmer to look at, compare against Bridges (dense)." }
};
// The order sets are listed on the home screen.
const SET_ORDER = ["crown", "dancefloor", "dancefloor2", "dancefloor1", "mud", "mud1", "potion", "bridgeDense", "bridgeOpen"];

// The raw ?set= value, whatever it is -- not filtered to ALL_SETS, since the
// caller also needs to recognise the reserved value "home" (see below).
function requestedSetParam() {
  try {
    return new URLSearchParams(window.location.search).get("set");
  } catch {
    return null;
  }
}

const GENTLE_KEY = "magmamia.gentle.v1";
const PREVIEW_KEY = "magmamia.preview.v1";

// How many level buttons the queue strip shows at once, and how far a
// triangle-button press shifts it (see renderLevelQueue): half the window, so
// one press moves the level that was in the middle to whichever end was
// pressed.
const QUEUE_WINDOW_SIZE = 9;
const QUEUE_STEP = Math.floor(QUEUE_WINDOW_SIZE / 2);

// A tiny, real level for the splash screen's hero art -- playable with the
// actual engine, not decoration. Push the block up into the magma to bridge
// it, then step across to the crown; the wall under the crown blocks the
// direct route, forcing the detour. Dying (stepping straight into the magma)
// just restarts it, same as any level.
const SPLASH_LEVEL_TEXT = ".a.*\n.A#\n@..";
const splash = { current: parseLevel(SPLASH_LEVEL_TEXT) };

const state = {
  view: "home", // "home" (pick a set), "levels" (pick a level within one) or "play".
  setKey: null, // Which of ALL_SETS is open, or null on the home screen.
  levelIndex: 0,
  initial: null,
  current: null,
  history: [], // Every earlier state, oldest first; its length is the move count.
  pushCounts: [], // Parallel to history: how many pushes had been made at each of those states.
  pushes: 0, // Pushes so far. The level's `optimum` is the fewest pushes that solve it.
  message: "",
  messageKind: "",
  solved: new Set(), // Indexes solved so far in the open set, remembered between visits.
  gentle: false, // Refuse lava moves instead of dying.
  preview: false, // Tag the cells a push would drop blocks on. Opt-in, off by default.
  hasPotions: false // Whether the current level uses potions at all, set by startLevel.
};

function currentSet() {
  return state.setKey ? ALL_SETS[state.setKey] : null;
}
function currentLevels() {
  const set = currentSet();
  return set ? set.levels : [];
}
function firstUnsolvedLevel() {
  const levels = currentLevels();
  const index = levels.findIndex((_, i) => !state.solved.has(i));
  return index >= 0 ? index : 0;
}

const elements = {
  splashScreen: document.querySelector("#splash-screen"),
  splashArt: document.querySelector("#splash-art"),
  enterDungeonButton: document.querySelector("#enter-dungeon-button"),
  homeScreen: document.querySelector("#home-screen"),
  modeList: document.querySelector("#mode-list"),
  levelsScreen: document.querySelector("#levels-screen"),
  levelsHomeButton: document.querySelector("#levels-home-button"),
  levelsContinueButton: document.querySelector("#levels-continue-button"),
  levelsTitle: document.querySelector("#levels-title"),
  levelsSubtitle: document.querySelector("#levels-subtitle"),
  levelsGrid: document.querySelector("#levels-grid"),
  levelsQueuePrev: document.querySelector("#levels-queue-prev"),
  levelsQueueNext: document.querySelector("#levels-queue-next"),
  playScreen: document.querySelector("#play-screen"),
  playLevelsButton: document.querySelector("#play-levels-button"),
  playLevelsGrid: document.querySelector("#play-levels-grid"),
  playQueuePrev: document.querySelector("#play-queue-prev"),
  playQueueNext: document.querySelector("#play-queue-next"),
  infoButton: document.querySelector("#info-button"),
  infoPanel: document.querySelector("#info-panel"),
  gentle: document.querySelector("#gentle-lava"),
  preview: document.querySelector("#show-preview"),
  board: document.querySelector("#board"),
  status: document.querySelector("#status"),
  undo: document.querySelector("#undo-button"),
  restart: document.querySelector("#restart-button"),
  next: document.querySelector("#next-button"),
  objectiveHelp: document.querySelector("#objective-help"),
  title: document.querySelector("#game-title")
};

loadPreferences();
elements.gentle.checked = state.gentle;
elements.preview.checked = state.preview;
elements.infoButton.addEventListener("click", toggleInfo);
elements.gentle.addEventListener("change", () => {
  state.gentle = elements.gentle.checked;
  savePreference(GENTLE_KEY, state.gentle ? "1" : "0");
});
elements.preview.addEventListener("change", () => {
  state.preview = elements.preview.checked;
  savePreference(PREVIEW_KEY, state.preview ? "1" : "0");
  render();
});
elements.undo.addEventListener("click", undo);
elements.restart.addEventListener("click", restart);
elements.next.addEventListener("click", () => startLevel(state.levelIndex + 1));
elements.board.addEventListener("click", handleBoardClick);
elements.splashArt.addEventListener("click", handleSplashBoardClick);
elements.levelsHomeButton.addEventListener("click", goHome);
elements.levelsContinueButton.addEventListener("click", () => startLevel(firstUnsolvedLevel()));
// Crown's real home is the splash now, not the levels-select grid (its own
// queue lives right here on the play screen); every other set still relies
// on the levels-select screen, so it keeps going back there.
elements.playLevelsButton.addEventListener("click", () => (state.setKey === "crown" ? showSplash() : openLevels(state.setKey)));
elements.enterDungeonButton.addEventListener("click", () => startLevel(firstUnsolvedLevel()));
document.addEventListener("keydown", handleKeyDown);

// Declared here (rather than nearer the functions that use them) because the
// routing block below calls showSplash()/openLevels() synchronously, during
// this same initial pass through the script -- a `const` declared after that
// point would still be in its temporal dead zone when a hoisted function
// reached for it, throwing and silently aborting the rest of that render()
// (this is exactly a bug that briefly shipped).
const meltTimers = new WeakMap(); // board element -> pending setTimeout handle, if any.
const queueWindows = new Map(); // level-queue container -> its own scroll window (see renderLevelQueue).

// The real front page is Seize the Crown's splash -- a bare link (from the hub
// site, or index.html with no query string) goes straight to it. The home
// screen (every set, for Michael's own review, not for a visitor) is reachable
// at ?set=home; an actual set still opens directly at ?set=<key>, unchanged.
const requestedParam = requestedSetParam();
if (requestedParam && ALL_SETS[requestedParam]) openLevels(requestedParam);
else if (requestedParam === "home") goHome();
else showSplash();

// --- Moving between the four screens -----------------------------------------

function showSplash() {
  state.view = "splash";
  state.setKey = "crown";
  loadSetPreferences(); // So "Enter the dungeon!" resumes progress, not level 1 every time.
  render();
}

function goHome() {
  state.view = "home";
  state.setKey = null;
  render();
}

// --- The splash screen's own tiny puzzle -------------------------------------

function attemptSplashMove(directionName) {
  if (isWon(splash.current, "reach")) return;
  const outcome = move(splash.current, directionName, { lavaFatal: true });
  if (outcome.result === "moved" || outcome.result === "pushed") splash.current = outcome.state;
  else if (outcome.result === "died") splash.current = parseLevel(SPLASH_LEVEL_TEXT); // Just restart, no fuss.
  renderSplash();
}

// A click on a square next to the player moves that way, same as the real board.
function handleSplashBoardClick(event) {
  const s = splash.current;
  const rect = elements.splashArt.getBoundingClientRect();
  const scale = (s.cols * CELL) / rect.width;
  const x = Math.floor(((event.clientX - rect.left) * scale) / CELL);
  const y = Math.floor(((event.clientY - rect.top) * scale) / CELL);
  const dx = x - (s.player % s.cols);
  const dy = y - Math.floor(s.player / s.cols);
  if (Math.abs(dx) + Math.abs(dy) !== 1) return;
  const directionName = Object.keys(DIRECTIONS).find((name) => DIRECTIONS[name].dx === dx && DIRECTIONS[name].dy === dy);
  attemptSplashMove(directionName);
}

function openLevels(key) {
  state.setKey = key;
  state.view = "levels";
  loadSetPreferences();
  render();
}

// --- Preferences: two global display settings, plus each set's own solved list --

// Browser storage may be missing or blocked, so every use is wrapped: the game
// works the same without it, it just forgets progress and settings.
function loadPreferences() {
  try {
    state.gentle = window.localStorage.getItem(GENTLE_KEY) === "1";
    state.preview = window.localStorage.getItem(PREVIEW_KEY) === "1"; // Off unless turned on.
  } catch {
    /* No saved preferences. */
  }
}

function loadSetPreferences() {
  state.solved = new Set();
  try {
    const solved = JSON.parse(window.localStorage.getItem(currentSet().key) || "[]");
    if (Array.isArray(solved)) solved.forEach((i) => Number.isInteger(i) && state.solved.add(i));
  } catch {
    /* No saved progress for this set. */
  }
}

// A set's solved count read straight from storage, so the home screen can show every
// set's progress without having to open each one first.
function solvedCountFor(key) {
  try {
    const solved = JSON.parse(window.localStorage.getItem(ALL_SETS[key].key) || "[]");
    return Array.isArray(solved) ? solved.length : 0;
  } catch {
    return 0;
  }
}

function savePreference(key, value) {
  try {
    window.localStorage.setItem(key, value);
  } catch {
    /* Progress just isn't remembered. */
  }
}

function toggleInfo() {
  const open = elements.infoPanel.hidden;
  elements.infoPanel.hidden = !open;
  elements.infoButton.setAttribute("aria-expanded", String(open));
}

// --- Playing a level ---------------------------------------------------------

function startLevel(index) {
  const levels = currentLevels();
  if (index < 0 || index >= levels.length) return;
  state.view = "play";
  state.levelIndex = index;
  state.initial = parseLevel(levels[index].text);
  state.hasPotions = state.initial.potions.some((p) => p === 1); // Only show the count if the level actually uses them.
  resetHistory();
  setMessage("", "");
  render();
}

function setMessage(text, kind) {
  state.message = text;
  state.messageKind = kind;
}

function objectiveOf(levelIndex) {
  return currentLevels()[levelIndex].objective || "reach";
}

function isSolved() {
  return isWon(state.current, objectiveOf(state.levelIndex));
}

function attemptMove(directionName) {
  if (isSolved()) return;
  const outcome = move(state.current, directionName, { lavaFatal: !state.gentle });
  if (outcome.result === "moved" || outcome.result === "pushed") {
    state.history.push(state.current);
    state.pushCounts.push(state.pushes);
    if (outcome.result === "pushed") state.pushes += 1;
    state.current = outcome.state;
    if (outcome.pickedUpPotion) setMessage("Picked up a potion.", "");
    else if (outcome.usedPotion) setMessage("The potion saved you -- but it's used up, so don't step onto lava again next.", "");
    else setMessage("", "");
    if (isSolved()) {
      state.solved.add(state.levelIndex);
      savePreference(currentSet().key, JSON.stringify([...state.solved]));
    }
  } else if (outcome.result === "refused") {
    setMessage(REFUSAL_TEXT[outcome.reason], "");
  } else {
    // Died: the level restarts, and with it the move count and undo history.
    resetHistory();
    setMessage(DEATH_TEXT[outcome.reason], "died");
  }
  render();
}

function undo() {
  if (state.history.length === 0) return;
  state.current = state.history.pop();
  state.pushes = state.pushCounts.pop();
  setMessage("", "");
  render();
}

function resetHistory() {
  state.current = state.initial;
  state.history = [];
  state.pushCounts = [];
  state.pushes = 0;
}

function restart() {
  resetHistory();
  setMessage("", "");
  render();
}

function handleKeyDown(event) {
  if (event.ctrlKey || event.metaKey || event.altKey) return;
  const tag = event.target.tagName;
  if (tag === "INPUT" || tag === "SELECT" || tag === "TEXTAREA") return;
  if (state.view === "splash") {
    const splashDirection = KEY_DIRECTIONS[event.key];
    if (splashDirection) {
      event.preventDefault();
      attemptSplashMove(splashDirection);
    }
    return;
  }
  if (state.view !== "play") return;
  const directionName = KEY_DIRECTIONS[event.key];
  if (directionName) {
    event.preventDefault();
    attemptMove(directionName);
  } else if (event.key === "z" || event.key === "Z") {
    undo();
  } else if (event.key === "r" || event.key === "R") {
    restart();
  } else if (event.key === "Enter" && isSolved() && !elements.next.hidden) {
    startLevel(state.levelIndex + 1);
  }
}

// A click on a square next to the player moves that way; anything else is ignored.
function handleBoardClick(event) {
  const s = state.current;
  const rect = elements.board.getBoundingClientRect();
  const scale = (s.cols * CELL) / rect.width;
  const x = Math.floor(((event.clientX - rect.left) * scale) / CELL);
  const y = Math.floor(((event.clientY - rect.top) * scale) / CELL);
  const dx = x - (s.player % s.cols);
  const dy = y - Math.floor(s.player / s.cols);
  if (Math.abs(dx) + Math.abs(dy) !== 1) return;
  const directionName = Object.keys(DIRECTIONS).find((name) => DIRECTIONS[name].dx === dx && DIRECTIONS[name].dy === dy);
  attemptMove(directionName);
}

// --- Rendering ----------------------------------------------------------------

function render() {
  elements.splashScreen.hidden = state.view !== "splash";
  elements.homeScreen.hidden = state.view !== "home";
  elements.levelsScreen.hidden = state.view !== "levels";
  elements.playScreen.hidden = state.view !== "play";
  if (state.view === "splash") renderSplash();
  else if (state.view === "home") renderHome();
  else if (state.view === "levels") renderLevels();
  else renderPlay();
}

function renderSplash() {
  drawBoard(elements.splashArt, splash.current);
  scheduleMelt(elements.splashArt, isWon(splash.current, "reach"));
}

// The "solved" indicator (see .board.is-solved in styles.css): the border --
// walls and the abyss alike -- fades away, rather than only a status line
// saying so. Delayed a beat rather than firing the instant the winning move
// lands, so it reads as a reaction to the win, not part of the move itself.
// (meltTimers itself is declared up near the top of the file -- see the
// comment there for why.)
function scheduleMelt(board, solved) {
  const pending = meltTimers.get(board);
  if (!solved) {
    if (pending) clearTimeout(pending);
    meltTimers.delete(board);
    board.classList.remove("is-solved");
    return;
  }
  if (pending || board.classList.contains("is-solved")) return;
  meltTimers.set(board, setTimeout(() => {
    board.classList.add("is-solved");
    meltTimers.delete(board);
  }, 500));
}

function renderHome() {
  elements.modeList.replaceChildren();
  for (const key of SET_ORDER) {
    const set = ALL_SETS[key];
    const button = document.createElement("button");
    button.type = "button";
    button.className = "mode-card";
    const title = document.createElement("span");
    title.className = "mode-title";
    title.textContent = set.title;
    const blurb = document.createElement("span");
    blurb.className = "mode-blurb";
    blurb.textContent = set.blurb;
    const progress = document.createElement("span");
    progress.className = "mode-progress";
    progress.textContent = `${solvedCountFor(key)}/${set.levels.length} solved`;
    button.append(title, blurb, progress);
    button.addEventListener("click", () => openLevels(key));
    elements.modeList.append(button);
  }
}

// The queue's own window (which slice of the level list its up-to-9 locked
// positions currently show) is kept separate from `state`, and keyed by
// container, since the two queues (levels screen, play screen) browse
// independently of each other. It re-centres on the current level whenever
// that (or the level count) changes; otherwise it's left alone, so browsing
// with the triangle buttons survives an unrelated re-render (e.g. a move on
// the play screen doesn't snap the strip back to centre).
function levelQueueWindow(container, currentIndex, total) {
  const size = Math.min(QUEUE_WINDOW_SIZE, total);
  const existing = queueWindows.get(container);
  if (existing && existing.currentIndex === currentIndex && existing.total === total) return existing;
  const half = Math.floor(size / 2);
  const start = Math.max(0, Math.min(currentIndex - half, total - size));
  const win = { start, currentIndex, total };
  queueWindows.set(container, win);
  return win;
}

// Shared by the levels screen and the panel under the board on the play
// screen. "Current" means different things in each: on the levels screen (not
// playing yet) it's a suggestion, the first unsolved level; on the play
// screen it's simply whichever level is actually open right now.
//
// Up to 9 locked button positions, the current level centred by default (see
// levelQueueWindow). A triangle-button press shifts the window by
// QUEUE_STEP (4) -- moving the level that was in the middle to that end of
// the strip -- clamped so it never runs past the first or last level, and
// each triangle hides itself once its end is already fully in view.
// `direction` is set only when this call is itself the result of such a
// press, so the freshly revealed buttons can slide in (see the
// .enter-left/.enter-right animation in styles.css); an ordinary re-render
// passes none and gets no animation, since the window hasn't moved.
function renderLevelQueue(container, prevButton, nextButton, currentIndex, direction) {
  const set = currentLevels();
  const total = set.length;
  const size = Math.min(QUEUE_WINDOW_SIZE, total);
  const win = levelQueueWindow(container, currentIndex, total);
  prevButton.hidden = win.start <= 0;
  nextButton.hidden = win.start + size >= total;
  prevButton.onclick = () => {
    win.start = Math.max(0, win.start - QUEUE_STEP);
    renderLevelQueue(container, prevButton, nextButton, currentIndex, "left");
  };
  nextButton.onclick = () => {
    win.start = Math.min(total - size, win.start + QUEUE_STEP);
    renderLevelQueue(container, prevButton, nextButton, currentIndex, "right");
  };
  container.replaceChildren();
  for (let i = 0; i < size; i++) {
    const index = win.start + i;
    const button = document.createElement("button");
    button.type = "button";
    button.textContent = String(index + 1);
    button.className = "level-button";
    if (direction) button.classList.add(`enter-${direction}`);
    if (state.solved.has(index)) button.classList.add("is-solved");
    if (index === currentIndex) button.classList.add("is-current");
    button.setAttribute("aria-label", `Level ${index + 1}${state.solved.has(index) ? ", solved" : ""}`);
    button.addEventListener("click", () => startLevel(index));
    container.append(button);
  }
}

function renderLevels() {
  const set = currentSet();
  elements.levelsTitle.textContent = set.title;
  elements.levelsSubtitle.textContent = set.blurb;
  const allSolved = state.solved.size >= set.levels.length;
  elements.levelsContinueButton.hidden = allSolved;
  elements.levelsContinueButton.textContent = state.solved.size === 0 ? "Start →" : "Continue →";
  renderLevelQueue(elements.levelsGrid, elements.levelsQueuePrev, elements.levelsQueueNext, allSolved ? -1 : firstUnsolvedLevel());
}

function renderPlay() {
  const set = currentSet();
  elements.title.textContent = state.setKey === "crown" ? "Magma Mia!" : `Magma Mia! — ${set.title}`;
  elements.playLevelsButton.setAttribute("aria-label", state.setKey === "crown" ? "Back to the front page" : "Back to levels");
  elements.objectiveHelp.textContent = OBJECTIVE_HELP[objectiveOf(state.levelIndex)];
  // Tags for where a push from here would drop blocks (see previewPushes).
  const chips = state.preview && !isSolved() ? previewPushes(state.current).flatMap((push) => push.landings) : [];
  drawBoard(elements.board, state.current, { chips });
  scheduleMelt(elements.board, isSolved());
  renderStatus();
  elements.undo.disabled = state.history.length === 0;
  elements.next.hidden = !(isSolved() && state.levelIndex + 1 < currentLevels().length);
  renderLevelQueue(elements.playLevelsGrid, elements.playQueuePrev, elements.playQueueNext, state.levelIndex);
}

function renderStatus() {
  const moves = state.history.length;
  elements.status.className = "status";
  if (isSolved()) {
    const last = state.levelIndex + 1 >= currentLevels().length;
    const lastSuffix = last ? " That's the last level for now." : "";
    // Push optimisation (moves, pushes, and the optimum comparison) is the point
    // of "Clear the dancefloor" -- tidying up efficiently is the game there. It
    // isn't the point of the other objectives, so their solved message stays plain.
    if (objectiveOf(state.levelIndex) === "all") {
      const optimum = currentLevels()[state.levelIndex].optimum;
      const pushes = `${state.pushes} ${state.pushes === 1 ? "push" : "pushes"}`;
      const versus = !optimum ? "" : state.pushes <= optimum ? " That's the optimum!" : ` The optimum is ${optimum}.`;
      elements.status.textContent = `Solved in ${moves} ${moves === 1 ? "move" : "moves"}, ${pushes}.${versus}${lastSuffix}`;
    } else {
      elements.status.textContent = `Solved!${lastSuffix}`;
    }
    elements.status.classList.add("is-won");
  } else {
    const potions = state.hasPotions ? ` · Potions: ${state.current.carried}` : "";
    const prefix = `Level ${state.levelIndex + 1} · Moves: ${moves} · Pushes: ${state.pushes}${potions}`;
    elements.status.textContent = state.message ? `${prefix} · ${state.message}` : prefix;
    if (state.messageKind === "died") elements.status.classList.add("is-died");
  }
}
